import "./globals.css";
import Head from "next/head";
import { poppins } from "./fonts";
import TopBar from "@/components/topBar";
import Footer from "@/components/footer";

export const metadata = {
  title: "CountryExplorer",
  description: "Generated by Next.js",
  icons: {
    icon: "/earth-icon.ico",
    // apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({ children = [] }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/earth-icon.ico" />
      </Head>
      <body className={`${poppins.className}`}>
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
